build.gradle, loopme-sdk/build.gradle, loopme-sdk/src/main/java/com/loopme/ad/AdParams.java, loopme-sdk/src/main/java/com/loopme/controllers/view/View360Controller.java, loopme-sdk/src/main/java/com/loopme/gdpr/GdprDialog.java, loopme-sdk/src/main/java/com/loopme/receiver/AdReceiver.java, loopme-sdk/src/main/java/com/loopme/request/RequestParamsUtils.java, loopme-sdk/src/main/java/com/loopme/request/RequestUtils.java, loopme-sdk/src/main/java/com/loopme/utils/Utils.java, loopme-sdk/src/main/java/com/loopme/video360/common/GLUtil.java, loopme-sdk/src/main/java/com/loopme/video360/strategy/interactive/MotionStrategy.java
NPE check corresponds to code inspector added
=> Preparation release 6.1.2

auto-tester/src/main/java/com/loopme/tester/ui/fragment/BaseFragment.java, auto-tester/src/main/java/com/loopme/tester/ui/view/ManualView.java, auto-tester/src/main/java/com/loopme/tester/utils/Utils.java, loopme-sdk/src/main/java/com/loopme/models/response/Ext.java, loopme-sdk/src/main/java/com/loopme/parser/ParseService.java, loopme-sdk/src/main/java/com/loopme/tracker/AdIds.java, loopme-sdk/src/main/java/com/loopme/tracker/TrackerManager.java, loopme-sdk/src/main/java/com/loopme/tracker/partners/ias/IasTracker.java, loopme-sdk/src/main/java/com/loopme/tracker/partners/ias/IasUrlProvider.java
-hide parent view in auto tester
-remove ias  monitoring tag
-set parameters in ias cm tag
=> Ias improvements

loopme-sdk/src/main/java/com/loopme/LoopMeSdk.java, loopme-sdk/src/main/java/com/loopme/Preferences.java, loopme-sdk/src/main/java/com/loopme/ad/LoopMeAd.java, loopme-sdk/src/main/java/com/loopme/debugging/LiveDebug.java, loopme-sdk/src/main/java/com/loopme/gdpr/ConsentType.java, loopme-sdk/src/main/java/com/loopme/gdpr/GdprChecker.java, loopme-sdk/src/main/java/com/loopme/gdpr/GdprWebView.java, loopme-sdk/src/main/java/com/loopme/request/AdvertisingIdClient.java, loopme-sdk/src/main/java/com/loopme/request/RequestBuilder.java, loopme-sdk/src/main/java/com/loopme/request/RequestParamsUtils.java, loopme-sdk/src/main/java/com/loopme/request/RequestUtils.java
Move consent data from imp.ext to user.ext, add regs.ext.gdpr obj
=> Publisher Gdpr consent string  support

loopme-sdk/src/main/java/com/loopme/gdpr/GdprChecker.java
Failed ad load by first launch while ignoring all instruction - fixed
=> GDPR ad load failed - fix

loopme-sdk/src/main/java/com/loopme/Constants.java, loopme-sdk/src/main/java/com/loopme/LoopMeSdk.java, loopme-sdk/src/main/java/com/loopme/parser/ParseService.java, loopme-sdk/src/main/java/com/loopme/tracker/partners/LoopMeTracker.java
feedback url changed, pass ad id token instead of creative id
=> Event SDK Feedback fix

build.gradle, loopme-sdk/src/main/AndroidManifest.xml, loopme-sdk/src/main/assets/mraid.js, loopme-sdk/src/main/java/com/loopme/bridges/mraid/MraidBridge.java, loopme-sdk/src/main/java/com/loopme/controllers/MraidController.java, loopme-sdk/src/main/java/com/loopme/loaders/AdFetchTask.java, loopme-sdk/src/main/java/com/loopme/loaders/AdFetchTaskByUrl.java, loopme-sdk/src/main/java/com/loopme/utils/ConnectionUtils.java, sample-banner/src/main/AndroidManifest.xml, sample-interstitial/src/main/AndroidManifest.xml, sample-interstitial/src/main/res/xml/network_security_config.xml
https://loopme.atlassian.net/browse/SDK-119
=> Sdk 119 fix html mraid creatives

bridges/appLovin/adapter/src/main/java/com/applovin/mediation/adapters/LoopmeMediationAdapter.java, bridges/appLovin/app/src/main/AndroidManifest.xml, bridges/appLovin/app/src/main/java/com/loopme/applovin/app/BannerActivity.java, bridges/appLovin/app/src/main/java/com/loopme/applovin/app/InterstitialActivity.java, bridges/appLovin/app/src/main/java/com/loopme/applovin/app/MainActivity.java, bridges/appLovin/app/src/main/java/com/loopme/applovin/app/RewardedVideoActivity.java, bridges/appLovin/app/src/main/res/layout/activity_banner.xml, bridges/appLovin/app/src/main/res/layout/activity_interstitial.xml, bridges/appLovin/app/src/main/res/layout/activity_main.xml, bridges/appLovin/app/src/main/res/layout/activity_rewarded.xml, bridges/appLovin/app/src/main/res/values/strings.xml, bridges/appLovin/app/src/main/res/xml/network_security_config.xml, loopme-sdk/src/main/java/com/loopme/request/RequestParamsUtils.java
Updates the AppLovin test app to provide interfaces to test banners and rewarded ads.
Adds banner functionality to the AppLovin test app and adapter.
Adds rewarded functionality to the AppLovin test app and adapter.
Adds an improvement to the SDK to send correct sizes if the banner view has been laid out.
=> Prepare AppLovin MAX Adapter for release

loopme-sdk/src/main/java/com/loopme/request/RequestParamsUtils.java
Adjusts the function that provides the size for interstitial requests to be based on device type and orientation.
[Related JIRA ticket](https://loopme.atlassian.net/browse/SDK-225)
=> Adjust interstitial sizes to be based on device type and orientation

loopme-sdk/src/main/java/com/loopme/utils/UiUtils.java
Issue related to API 34 and higher
https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported
=> full screen rich media ad can't be closed

loopme-sdk/src/main/java/com/loopme/Constants.java, loopme-sdk/src/main/java/com/loopme/views/CloseButton.java, loopme-sdk/src/main/res/values/dimens.xml
Reduce False clicks on close button by increasing clickable area
=> Set Action icons click area to 60dp

bridges/admob/adapter/src/main/java/com/admob/mediation/adapters/LoopMeRewardedListener.java, bridges/admob/app/src/main/java/com/loopme/admob/app/InterstitialActivity.java, bridges/appLovin/adapter/src/main/java/com/applovin/mediation/adapters/LoopmeMediationAdapter.java, bridges/ironSource/adapter/src/main/java/com/ironsource/adapters/custom/loopme/LoopmeCustomRewardedVideo.java, loopme-sdk/src/main/java/com/loopme/LoopMeInterstitial.java, loopme-sdk/src/main/java/com/loopme/LoopMeInterstitialGeneral.java, loopme-sdk/src/main/java/com/loopme/request/RequestBuilder.java
SDK-114 Added rewarded fields to ortb request
=> SDK-114 Added rewarded fields to ortb request

loopme-sdk/src/main/java/com/loopme/loaders/FileLoaderNewImpl.java
subtask of https://loopme.atlassian.net/browse/SDK-304
=> [SDK-304]_video_error_handling _update_error_msg

README_CHINESE.md, loopme-sdk/src/main/AndroidManifest.xml, loopme-sdk/src/main/java/com/loopme/bridges/Bridge.java, loopme-sdk/src/main/java/com/loopme/views/webclient/AdViewChromeClient.java
removed not critical permissions and usages:  
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.RECORD_AUDIO" />
<uses-permission android:name="android.permission.VIBRATE" />
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
location permissions which requested by publishers to be removed have needed usages: 
location is used currently in RequestBuilder 
.put(GEO, (location != null) ? new JSONBuilder()
.put(LAT, (float) location.getLatitude())
.put(LON, (float) location.getLongitude())
etc.
=> SDK-348_permissions_publisher_ask_to_remove

bridges/appLovin/adapter/build.gradle.kts
latest sdk version: https://developers.applovin.com/en/android/overview/manual-integration/
=> SDK-355_applovin_version_upgrade

bridges/admob/adapter/src/main/java/com/admob/mediation/adapters/LoopMeMediationAdapter.java, bridges/appLovin/adapter/src/main/java/com/applovin/mediation/adapters/LoopmeMediationAdapter.java, bridges/ironSource/adapter/src/main/java/com/ironsource/adapters/custom/loopme/LoopmeCustomAdapter.java, loopme-sdk/src/main/java/com/loopme/AdWrapper.java, loopme-sdk/src/main/java/com/loopme/Constants.java, loopme-sdk/src/main/java/com/loopme/LoopMeBanner.java, loopme-sdk/src/main/java/com/loopme/LoopMeBannerGeneral.java, loopme-sdk/src/main/java/com/loopme/LoopMeInterstitial.java, loopme-sdk/src/main/java/com/loopme/LoopMeInterstitialGeneral.java, loopme-sdk/src/main/java/com/loopme/LoopMeSdk.java, loopme-sdk/src/main/java/com/loopme/ad/LoopMeAd.java, loopme-sdk/src/main/java/com/loopme/controllers/display/BaseTrackableController.java, loopme-sdk/src/main/java/com/loopme/debugging/Params.java, loopme-sdk/src/main/java/com/loopme/tracker/partners/LoopMeTracker.java
enhance error reporting mediation and placement
=> SDK-305_reporting-placement-and-mediation-fields

bridges/ironSource/adapter/src/main/java/com/ironsource/adapters/custom/loopme/LoopmeCustomRewardedVideo.java
=> SDK-377_fix-rewarded-no-impression-level-data

loopme-sdk/src/main/java/com/loopme/Constants.java, loopme-sdk/src/main/java/com/loopme/LoopMeBanner.java, loopme-sdk/src/main/java/com/loopme/LoopMeBannerGeneral.java, loopme-sdk/src/main/java/com/loopme/LoopMeSdk.java, loopme-sdk/src/main/java/com/loopme/ad/AdParams.java, loopme-sdk/src/main/java/com/loopme/ad/AdParamsBuilder.java, loopme-sdk/src/main/java/com/loopme/ad/LoopMeAd.java, loopme-sdk/src/main/java/com/loopme/debugging/LiveDebug.java, loopme-sdk/src/main/java/com/loopme/debugging/Params.java, loopme-sdk/src/main/java/com/loopme/models/response/Bid.java, loopme-sdk/src/main/java/com/loopme/parser/ParseService.java, loopme-sdk/src/main/java/com/loopme/tracker/partners/LoopMeTracker.java
- added fields to error object or errors triggered post response
- fixed typos 
- code clean up
=> SDK-303_SDK-error-reporting

loopme-sdk/src/main/java/com/loopme/request/RequestBuilder.java
fix passing GDPR consent string
=> SDK-366_fix-GDPR-string-not-recieved

loopme-sdk/src/main/java/com/loopme/request/RequestBuilder.java, loopme-sdk/src/main/java/com/loopme/request/RequestUtils.java
additional parameters added to outgoing request
=> [SDK-362][SDK-363]-battery_parameters-to-outgoing-request

loopme-sdk/src/main/assets/mraid.js, loopme-sdk/src/main/java/com/loopme/LoopMeGestureListener.java, loopme-sdk/src/main/java/com/loopme/ad/LoopMeAd.java, loopme-sdk/src/main/java/com/loopme/bridges/MraidBridge.java, loopme-sdk/src/main/java/com/loopme/bridges/MraidBridgeCommand.java, loopme-sdk/src/main/java/com/loopme/controllers/MraidController.java, loopme-sdk/src/main/java/com/loopme/controllers/display/DisplayModeResolver.java, loopme-sdk/src/main/java/com/loopme/views/MraidView.java
SDK added protection to prevent auto-expand or auto-redirect that is not user-initiated
=> SDK-343_fix-auto-expandable&auto-redirect-creative

bridges/appLovin/adapter/src/main/java/com/applovin/mediation/adapters/LoopmeMediationAdapter.java
allow banner ad serving compatible with Applovin SDK version 12.6
=> SDK-417-getAdaptiveSize-method-not-found

loopme-sdk/src/main/java/com/loopme/request/RequestUtils.java
batterySaver mode capturing for Xiaomi and Huawei
=> SDK-362_fix_batterySaver_for_Huawei_Xiaomi

loopme-sdk/src/main/java/com/loopme/ad/LoopMeAd.java, loopme-sdk/src/main/java/com/loopme/bridges/MraidBridge.java, loopme-sdk/src/main/java/com/loopme/bridges/MraidBridgeCommand.java, loopme-sdk/src/main/java/com/loopme/controllers/MraidController.java
Fixed case when click-to-expand stop working
=> [SDK-343] auto-expandable creative on 320x50 banner slot

loopme-sdk/src/main/java/com/loopme/debugging/Params.java, loopme-sdk/src/main/java/com/loopme/tracker/partners/LoopMeTracker.java, loopme-sdk/src/main/java/com/loopme/utils/SessionManager.java
added integration of session_id within error reporting
=> SDK-468/Implement-session_id-data-filed

loopme-sdk/src/main/java/com/loopme/controllers/display/DisplayControllerLoopMe.java, loopme-sdk/src/main/java/com/loopme/controllers/display/DisplayControllerVast.java, loopme-sdk/src/main/java/com/loopme/controllers/display/DisplayControllerVpaid.java, loopme-sdk/src/main/java/com/loopme/controllers/display/VastWebView.java, loopme-sdk/src/main/java/com/loopme/views/MraidView.java, loopme-sdk/src/main/java/com/loopme/views/webclient/AdViewChromeClient.java
added missing parameters for clear error tracking within AdViewChromeClient
=> SDK-474/fields-empty-for-Error-from-JS

loopme-sdk/src/main/java/com/loopme/request/RequestBuilder.java
=> SDK-561/-no-GDPR-string-picked-up

loopme-sdk/src/main/java/com/loopme/Constants.java
=> SDK-565/updated-endpoint

loopme-sdk/src/main/java/com/loopme/request/RequestBuilder.java
calculated pxratio signal and included in ad requests
=> SDK-560/implement-pxratio-field

loopme-sdk/src/main/java/com/loopme/models/Errors.java
aligned naming for error with ios platform
=> SDK-482/align_error_event_naming_with_ios

loopme-sdk/src/main/java/com/loopme/Constants.java
This reverts commit b307902cf80af7a1325c89eb7f1a9699eb2359ef.
=> Revert SDK-565 "updated endpoint"
